//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp03.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryOfCompetitionId { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryOfCompetition CategoryOfCompetition { get; set; }
    }
}
