//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp03.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionService
    {
        public int Id { get; set; }
        public int ServiceTypeId { get; set; }
        public decimal CoordinateX { get; set; }
        public decimal CoordinateY { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
    }
}
