//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp03.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Judger
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int UserId { get; set; }
        public int CompetitionId { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
