//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp03.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int SponsorId { get; set; }
        public int CategoryOfSponsorshipId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Count { get; set; }
        public int EventId { get; set; }
    
        public virtual CategoryOfSponsorship CategoryOfSponsorship { get; set; }
        public virtual EventCompetition EventCompetition { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
