//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp03.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamCompetition
    {
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public string CompetitorId { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> StationNumber { get; set; }
        public int EventCompetitionId { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Competitior Competitior { get; set; }
        public virtual EventCompetition EventCompetition { get; set; }
    }
}
